{{- if .Values.mongo.uri }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "releasecraft.fullname" . }}-mongo-secret
type: Opaque
data:
  # Store the URI base64-encoded; Helm will not encode for you here, so we use tpl to place raw value
  uri: {{ .Values.mongo.uri | b64enc | quote }}
{{- end }}
